
services:
  frontend:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: filmesdb
    ports:
      - "3309:3309"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
